services:
  storage_api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGETARCH: ${BUILD_ARCH}
    platform: ${BUILD_PLATFORM}
    container_name: storage-api
    image: fluxconfig.storage.api:dev
    restart: always
    env_file:
      - ./.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Dockerfile build optimization
      - DOTNET_EnableWriteXorExecute = 0
      - DOTNET_NUGET_SIGNATURE_VERIFICATION = false
    networks:
      - fcs-network
    ports:
      - ${STORAGE_API_PORT}:7077
    volumes:
      - ${EXTERNAL_CERT_PATH}:/https/certs:ro
    depends_on:
      - database
  
  database:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_DATABASE: "configurations"
    networks:
      - fcs-network
    ports:
      - ${MONGO_PORT}:27017

volumes:
  mongo-data:
    driver: local

networks:
  fcs-network:
    driver: bridge
  