services:
  storage_api:
      env_file:
        - .env
      build:
        context: .
        dockerfile: Dockerfile
        args:
          TARGETARCH: ${BUILD_ARCH}
      platform: ${BUILD_PLATFORM}
      container_name: storage-api
      restart: always
      networks:
        - app-network
      environment:
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - DOTNET_EnableWriteXorExecute = 0
        - DOTNET_NUGET_SIGNATURE_VERIFICATION = false
      ports:
        - ${STORAGE_API_PORT}:443
      depends_on:
        - database
      
  database:
      image: mongo:latest
      container_name: mongo-db
      restart: always
      volumes:
        - mongo-data:/data/db
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      networks:
        - app-network
      env_file:
        - .env
      environment:
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
        MONGO_INITDB_DATABASE: "configurations"
      ports:
        - ${MONGO_PORT}:27017
        
volumes:
  mongo-data:
    driver: local
    
networks:
  app-network:
    driver: bridge
  