services:
  storage_api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGETARCH: ${BUILD_ARCH}
    platform: ${BUILD_PLATFORM}
    container_name: fc-storage-dev
    image: fluxconfig.storage:dev
    restart: always
    env_file:
      - ./.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Dockerfile build optimization
      - DOTNET_EnableWriteXorExecute = 0
      - DOTNET_NUGET_SIGNATURE_VERIFICATION = false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - fcs-network
    ports:
      - ${STORAGE_API_PORT}:7077
    volumes:
      - ${EXTERNAL_CERT_PATH}:/https/certs:ro
    depends_on:
      - database
  
  database:
    image: fluxconfig.mongo:dev
    container_name: fc-mongo-dev
    restart: always
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
    networks:
      - fcs-network

volumes:
  mongo-data:
    driver: local

networks:
  fcs-network:
    driver: bridge
  