services:
  storage_api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGETARCH: ${BUILD_ARCH}
    platform: ${BUILD_PLATFORM}
    container_name: storage-api
    image: fluxconfig.storage.api
    restart: always
    env_file:
      - ./.env
    environment:
      - DOTNET_GENERATE_ASPNET_CERTIFICATE = false
      - ASPNETCORE_HTTPS_PORT = 443
      - ASPNETCORE_URLS=https://0.0.0.0:443
      # Dockerfile build optimization
      - DOTNET_EnableWriteXorExecute = 0
      - DOTNET_NUGET_SIGNATURE_VERIFICATION = false
    networks:
      - app-network
    ports:
      - ${STORAGE_API_PORT}:443
    depends_on:
      - database
  
  database:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_DATABASE: "configurations"
    networks:
      - app-network
    ports:
      - ${MONGO_PORT}:27017

volumes:
  mongo-data:
    driver: local

networks:
  app-network:
    driver: bridge
  