name: "Publish FCS images CD"

on:
  release:
    types: [published]
    
env:
  REGISTRY: docker.io

jobs:
  publish_fcs_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        include:
          - build_context: .
            build_dockerfile_path: ./Dockerfile
            build_image_name: fluxconfig/fluxconfig.storage
          - build_context: mongo_image
            build_dockerfile_path: mongo_image/Dockerfile
            build_image_name: fluxconfig/fluxconfig.mongo
    
    if: startsWith(github.event.release.tag_name, 'v')
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and publish image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.build_context }}
          file: ${{ matrix.build_dockerfile_path }}
          platforms: linux/arm64, linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ matrix.build_image_name }}:${{ steps.extract_version.outputs.version }}
            ${{ env.REGISTRY }}/${{ matrix.build_image_name }}:latest